export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_DOCTYPE_INIT = 'FETCH_DOCTYPE_INIT';
export const FETCH_DOCTYPE_SUCCESS = 'FETCH_DOCTYPE_SUCCESS';
export const FETCH_DOCTYPE_FAIL = 'FETCH_DOCTYPE_FAIL';

export const FETCH_FY_INIT = 'FETCH_FY_INIT';
export const FETCH_FY_SUCCESS = 'FETCH_FY_SUCCESS';
export const FETCH_FY_FAIL = 'FETCH_FY_FAIL';

export const FETCH_REGDATA_INIT = 'FETCH_REGDATA_INIT';
export const FETCH_REGDATA_SUCCESS = 'FETCH_REGDATA_SUCCESS';
export const FETCH_REGDATA_FAIL = 'FETCH_REGDATA_FAIL';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';